// AUTO-GENERATED by scripts/gen-studio-example-videos.mjs — do not edit.
// Short Grok i2v clips for the template gallery (animate the still examples).
export const TEMPLATE_EXAMPLE_VIDEOS: Record<string, string> = {
  "birthday-party": "/studio_examples/birthday-party.mp4",
  "new-year-wish": "/studio_examples/new-year-wish.mp4",
  "daily-vlog": "/studio_examples/daily-vlog.mp4",
  "morning-stretch": "/studio_examples/morning-stretch.mp4",
  "noir-detective": "/studio_examples/noir-detective.mp4",
  "anime-opening": "/studio_examples/anime-opening.mp4",
  "dance-loop": "/studio_examples/dance-loop.mp4",
  "reaction-shock": "/studio_examples/reaction-shock.mp4"
};
