// AUTO-GENERATED by scripts/gen-studio-examples.mjs — do not edit by hand.
// Mascot-starring Grok example art for the Studio style picker + template gallery.
export const STYLE_EXAMPLES: Record<string, string> = {
  "cinematic": "/studio_styles/cinematic.jpg",
  "anime": "/studio_styles/anime.jpg",
  "photorealistic": "/studio_styles/photorealistic.jpg",
  "watercolor": "/studio_styles/watercolor.jpg",
  "pixar": "/studio_styles/pixar.jpg",
  "pixel": "/studio_styles/pixel.jpg"
};
export const TEMPLATE_EXAMPLES: Record<string, string> = {
  "birthday-party": "/studio_examples/birthday-party.jpg",
  "new-year-wish": "/studio_examples/new-year-wish.jpg",
  "daily-vlog": "/studio_examples/daily-vlog.jpg",
  "morning-stretch": "/studio_examples/morning-stretch.jpg",
  "noir-detective": "/studio_examples/noir-detective.jpg",
  "anime-opening": "/studio_examples/anime-opening.jpg",
  "dance-loop": "/studio_examples/dance-loop.jpg",
  "reaction-shock": "/studio_examples/reaction-shock.jpg",
  "cutie-dance": "/studio_examples/cutie-dance.jpg",
  "glow-up": "/studio_examples/glow-up.jpg",
  "runway-fashion": "/studio_examples/runway-fashion.jpg",
  "pov-talk": "/studio_examples/pov-talk.jpg",
  "tiny-mukbang": "/studio_examples/tiny-mukbang.jpg",
  "retro-anime-op": "/studio_examples/retro-anime-op.jpg",
  "phonk-flex": "/studio_examples/phonk-flex.jpg",
  "spooky-cute-costume": "/studio_examples/spooky-cute-costume.jpg",
  "hanbok-harvest-moon": "/studio_examples/hanbok-harvest-moon.jpg",
  "cozy-snow-day": "/studio_examples/cozy-snow-day.jpg",
  "duet-dance": "/studio_examples/duet-dance.jpg",
  "glow-up-timelapse": "/studio_examples/glow-up-timelapse.jpg",
};
