// AUTO-GENERATED by scripts/gen-studio-examples.mjs — do not edit by hand.
// Real Grok-rendered example art for the Studio style picker + template gallery.
export const STYLE_EXAMPLES: Record<string, string> = {
  "cinematic": "/studio_styles/cinematic.jpg",
  "anime": "/studio_styles/anime.jpg",
  "photorealistic": "/studio_styles/photorealistic.jpg",
  "watercolor": "/studio_styles/watercolor.jpg",
  "pixar": "/studio_styles/pixar.jpg",
  "pixel": "/studio_styles/pixel.jpg"
};
export const TEMPLATE_EXAMPLES: Record<string, string> = {
  "birthday-party": "/studio_examples/birthday-party.jpg",
  "new-year-wish": "/studio_examples/new-year-wish.jpg",
  "daily-vlog": "/studio_examples/daily-vlog.jpg",
  "morning-stretch": "/studio_examples/morning-stretch.jpg",
  "noir-detective": "/studio_examples/noir-detective.jpg",
  "anime-opening": "/studio_examples/anime-opening.jpg",
  "dance-loop": "/studio_examples/dance-loop.jpg",
  "reaction-shock": "/studio_examples/reaction-shock.jpg"
};
